FROM python:3.12-slim


# Chrome v114
ENV CHROME_VERSION=114.0.5735.90-1
ENV CHROMEDRIVER_VERSION=114.0.5735.90

# Install system dependencies
RUN apt-get update && apt-get install -y \
    curl wget unzip gnupg2 \
    xvfb x11-utils libxi6 libgconf-2-4 libnss3 libxss1 \
    libxcomposite1 libxcursor1 libxdamage1 libxrandr2 \
    libasound2 libatk1.0-0 libgtk-3-0 libgbm1 libxshmfence1 \
    fonts-liberation xdg-utils \
    && rm -rf /var/lib/apt/lists/*

# Install Chrome
RUN wget -O google-chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb && \
    apt-get update && \
    apt-get install -y ./google-chrome.deb || apt-get -f install -y && \
    rm google-chrome.deb

# Install matching ChromeDriver
RUN wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip && \
    unzip /tmp/chromedriver.zip -d /usr/local/bin/ && \
    chmod +x /usr/local/bin/chromedriver && \
    rm /tmp/chromedriver.zip


# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install dlt[gs]
RUN pip install dlt[parquet]

#install unmet dependencies
RUN apt-get -f install -y

#Clean up old user data on every run
RUN rm -rf /tmp/.com.google.Chrome*

# Copy app files
COPY . /app
WORKDIR /app

# Set display for Xvfb
ENV DISPLAY=:99

# Make port 8888 available to the world outside this container
EXPOSE 8888

CMD ["sh", "-c", "Xvfb :99 -screen 0 1920x1080x24 & python Data_Ingestion.py || tail -f /dev/null"]



